### ISSUE TITLE
Class 'Ipay88\Request\RequestBuilder' not found

### ISSUE THREAD

**Issue by svs22121990** [Kyrax324/laravel-ipay88#1]
Hi,

Getting error 
[2021-12-04 16:57:41] local.ERROR: Class 'Ipay88\Request\RequestBuilder' not found {"userId":11,"exception":"[object] (Error(code: 0): Class 'Ipay88\\Request\\RequestBuilder' not found at /var/www/html/leoNew/app/Http/Controllers/IPay88PaymentController.php:22)
[stacktrace]
#0 /var/www/html/leoNew/app/Http/Controllers/CheckoutController.php(44): App\\Http\\Controllers\\IPay88PaymentController->pay()

I have followed all the installation steps. Using below code in a controller

use Ipay88\Request\RequestBuilder as IPay88RequestBuilder;
use Ipay88\Responses\Response as IPay88Response;

public function pay()
    {
        $builder = new IPay88RequestBuilder();
        $builder->setRefNo(1);
        $builder->setAmount(1);
        $builder->setCurrency('MYR');
        $builder->setProdDesc('Sample Prod Desc');
        $builder->setUserName('Sample User Name');
        $builder->setUserEmail('Sample User Email');
        $builder->setUserContact('Sample User Contact');
        $builder->setResponseURL(route('ipay88.response_url'));
        $builder->setBackendURL(route('ipay88.backend_url'));

        return $builder->loadPaymentFormView();

    }

Please help me resolve this issue.

Regards,

**Comment by Kyrax324** [comment]
Hi @svs22121990 ,  thank you for creating this issue.

I believe that its is due to case-sensitive of the package path in Linux OS. 
Can you try again by changing the `use Ipay88\...` to `use IPay88\...`  as below ? :

```diff
- use Ipay88\Request\RequestBuilder as IPay88RequestBuilder;
+ use IPay88\Request\RequestBuilder as IPay88RequestBuilder;
- use Ipay88\Responses\Response as IPay88Response;
+ use IPay88\Responses\Response as IPay88Response;
```

Do let me know if this can resolve your issue.
Thank you very much for your valuable feedback. 😸

**Comment by svs22121990** [comment]
Hi,

Thanks for your reply !

I tried making the page but, it did not work. PFA Code screenshot. Yes, the code is deployed on Linux Server.

Class 'IPay88\Requests\RequestBuilder' not found

<img width="1395" alt="Screenshot 2021-12-05 at 1 14 44 PM" src="https://user-images.githubusercontent.com/26024356/144738249-b70d085f-4c91-40d6-8f42-2a3b8107a2f5.png">

**Comment by Kyrax324** [comment]
Hi @svs22121990 , may I know which laravel version you using ?

Maybe you can try manually add the service provider in your `config/app.php` file:

```php
'providers' => [
    // ...
    IPay88\IPay88ServiceProvider::class,
];
```

**Comment by svs22121990** [comment]
Hi,

I am using "laravel/framework": "^8.0"

When I manually add the provider I get below error

Class 'IPay88\IPay88ServiceProvider' not found
<img width="1440" alt="Screenshot 2021-12-05 at 4 09 44 PM" src="https://user-images.githubusercontent.com/26024356/144743147-cf6e078b-eda4-44e0-99e7-60b9162d10f9.png">

Regards,

**Comment by Kyrax324** [comment]
Hi @svs22121990 , this issue is quite new to me. 

Perhaps you can try with the below commands:

```
composer install
composer dump-autoload
```
and cross-check is the packages exists under /vendor folders

You can also discard your changes on the "manually adding the provider", since this package does support auto-discover.

**Comment by svs22121990** [comment]
Hi,

Yes, It's a strange issue. 

I tried running the commands that also didn't work. Package exists in vendor folder as well. Please let me know if you have any solution
<img width="328" alt="Screenshot 2021-12-05 at 11 24 06 PM" src="https://user-images.githubusercontent.com/26024356/144757709-384cf78b-8ede-4ff6-99f9-7ac7b81129e3.png">
.

**Comment by Kyrax324** [comment]
Hi @svs22121990 , sorry for unavailable to solve your issue. I will left this issue open until it's resolved.

But once again, thank you very much for your valuable feedback. 😸

**Comment by svs22121990** [comment]
Hi,

I tried reinstalling the package and it worked for me. So, the issue is fixed now. 

I am not getting response from iPay88. 
<img width="1440" alt="Screenshot 2021-12-25 at 7 42 58 PM" src="https://user-images.githubusercontent.com/26024356/147386891-c56b9444-9343-421f-90f5-d9e716f049ea.png">

Transactions are showing on iPay88. Can you please help resolve this ?
<img width="906" alt="Screenshot 2021-12-25 at 7 42 34 PM" src="https://user-images.githubusercontent.com/26024356/147386901-a8ccd4ba-d328-404d-bc0d-d5bf3adc0ac4.png">

**Comment by Kyrax324** [comment]
hi @svs22121990 , sorry for late response.

It's good to know that your issue have been solved, I will mark this issue as closed.

Once again feedback is much valuable to me.

**Comment by aashwiin8** [comment]
I faced the same issue using this package however, my fix was to change 
`use IPay88\Request\RequestBuilder` to
`use IPay88\Requests\RequestBuilder`
added as 's' for Request
